'use client';

import { CalendarX2, Loader2 } from 'lucide-react';
import { useState } from 'react';

import { useMeetingArtifacts } from '@/features/brain/hooks/use-meeting-artifacts';
import { formatDateTime } from '@/features/brain/lib/format';
import { EmptyState } from '@/shared/ui/feedback/empty-state';
import { InputDropdown } from '@/shared/ui/input';

import { MeetingAgendaSection } from './meeting-agenda-section';
import { MeetingProtocolSection } from './meeting-protocol-section';

import type { CalendarEventListItem } from '@/entities/event';

/**
 * "Протокол и агенда" tab body: a meeting picker over the organization's
 * meetings, and — for the selected one — the protocol (summary of the meeting
 * that happened) and the agenda (of the next meeting in the series). Both
 * artifacts are fetched together on selection and can be regenerated by a
 * manager. The dropdown search matches the full label (title + date), so a date
 * fragment like "05.06" finds the meeting.
 * @param root0 - props.
 * @param root0.meetings - organization meetings for the picker.
 * @param root0.canManage - whether regenerate controls are shown (tab is manager-gated).
 */
export function MeetingProtocolAgenda({
  meetings,
  canManage = true,
}: {
  meetings: CalendarEventListItem[];
  canManage?: boolean;
}) {
  const [selectedId, setSelectedId] = useState<string>(
    meetings.length > 0 ? String(meetings[0].id) : '',
  );
  const numericId = selectedId ? Number(selectedId) : null;

  const {
    summary,
    agenda,
    summaryDraft,
    agendaDraft,
    loading,
    error,
    regeneratingSummary,
    regeneratingAgenda,
    busyDraftId,
    regenerateSummary,
    regenerateAgenda,
    approveDraft,
    rejectDraft,
  } = useMeetingArtifacts(numericId);

  if (meetings.length === 0) {
    return (
      <EmptyState
        icon={CalendarX2}
        title='Нет доступных встреч'
        description='Протокол и агенда появятся после обработанных встреч.'
      />
    );
  }

  const meetingOptions = meetings.map((meeting) => {
    return {
      value: String(meeting.id),
      label: `${meeting.title} — ${formatDateTime(meeting.starts_at)}`,
    };
  });

  return (
    <div className='flex flex-col gap-5'>
      <div className='max-w-xl'>
        <InputDropdown
          label='Митинг'
          options={meetingOptions}
          value={selectedId}
          onChange={(value) => {
            setSelectedId(Array.isArray(value) ? (value[0] ?? '') : value);
          }}
          placeholder='Выберите митинг'
        />
      </div>

      {error && (
        <div className='rounded-[var(--radius-card)] border border-[var(--danger-bg)] bg-[var(--danger-bg)]/40 px-4 py-3 text-sm text-[var(--danger)]'>
          {error}
        </div>
      )}

      {!error && loading && (
        <div className='flex items-center justify-center gap-3 py-16 text-sm text-muted-foreground'>
          <Loader2 className='h-5 w-5 animate-spin text-[var(--primary)]' />
          Загрузка…
        </div>
      )}

      {!error && !loading && (
        <>
          <MeetingProtocolSection
            summary={summary}
            draft={summaryDraft}
            canManage={canManage}
            onRegenerate={regenerateSummary}
            regenerating={regeneratingSummary}
            onApproveDraft={() => {
              if (summaryDraft) approveDraft(summaryDraft.id);
            }}
            onRejectDraft={() => {
              if (summaryDraft) rejectDraft(summaryDraft.id);
            }}
            draftBusy={summaryDraft != null && busyDraftId === summaryDraft.id}
          />
          <MeetingAgendaSection
            agenda={agenda}
            draft={agendaDraft}
            canManage={canManage}
            onRegenerate={regenerateAgenda}
            regenerating={regeneratingAgenda}
            onApproveDraft={() => {
              if (agendaDraft) approveDraft(agendaDraft.id);
            }}
            onRejectDraft={() => {
              if (agendaDraft) rejectDraft(agendaDraft.id);
            }}
            draftBusy={agendaDraft != null && busyDraftId === agendaDraft.id}
          />
        </>
      )}
    </div>
  );
}
